### ISSUE TITLE
Make variables the same color as a property value

### ISSUE THREAD

**Issue by SYNTAG** [rainje/Monokai-Dark-Soda#3]
You used to have it in a previous update where the $variable was #ae81ff but now you have it to where variables are blue like this #66d9ef

Can you please change it back to the way it was. I think having the variables the same color as the property looks confusing, as they should be separate. I understand the intent behind separating variables from values, but I think making it the same color as a value was the right idea.

**Comment by rainje** [comment]
Yup, that's why I didn't push that update to Brackets. I still don't know if I will. Thanks for sharing your thoughts ;)

**Comment by rainje** [comment]
Back to old attributes colors.

**Comment by syntag** [comment]
Bump. This issue was not fixed in the latest patch. Variables are still the same color as CSS Properties.
