### ISSUE TITLE
Collapse icons are missing 

### ISSUE THREAD

**Issue by alemdq** [rainje/Monokai-Dark-Soda#4]
http://i.imgur.com/r5Oylzi.png

**Comment by rainje** [comment]
Hmm weird, the theme uses the default brackets font and this character should be included.

http://www.fileformat.info/info/unicode/char/2335/browsertest.htm

Here's my font family brackets setting 'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace
