### ISSUE TITLE
Missing character when code folding is collapsed

### ISSUE THREAD

**Issue by jerryyan1990** [rainje/Monokai-Dark-Soda#6]
![qq 20150829154238](https://cloud.githubusercontent.com/assets/12929365/9560980/f5fbb97e-4e64-11e5-8b57-f90942519b4f.png)

@rainje as you can see!

**Comment by rainje** [comment]
Similar to #4, not sure why it's happening.

Can you try editing the main.css of the theme
Change this:
```
.CodeMirror-foldgutter-open:after {
  content: "⌵";
  font-size: 1.3em;
  color: #767676;
}
```
To:
```
.CodeMirror-foldgutter-open:after {
  content: "\2335";
  font-size: 1.3em;
  color: #767676;
}
```

Using Win7/10 and I can't replicate the issue, I also have no special font installed.

**Comment by SYNTAG** [comment]
I'm having the same issue. I must not have the character on my computer then if I don't see the character on Google Chrome either. http://i.imgur.com/fpkW5bJ.png

Still have no clue how to install that character...

**Comment by rainje** [comment]
http://www.utf8icons.com/character/9013/countersink
http://chars.suikawiki.org/char/2335

I think I get it now, it seems this char works with latin1 windows (iso-8859-1) and not with many others. 

I'll try to find a new char that does work with mostly everything (why can't windows use UTF8, that'd solve it all).

**Comment by rainje** [comment]
Does this one work for you ? " ˅ "

**Comment by SYNTAG** [comment]
Yeah that character works for me. However, I know on my Windows 7 computer I can see the UTF-8 character just fine. So it can't be all Windows, or maybe I just don't have a required font or something?

**Comment by rainje** [comment]
I had no font installed for win7 or win10 and never had this issue, I think that's more of a regional windows encoding problem.

I'm sure there's an simple explanation.

**Comment by SYNTAG** [comment]
I'll report back if I find anything.

**Comment by rainje** [comment]
I'll keep it opened for now.

**Comment by joeky888** [comment]
Check this [https://github.com/adobe/brackets/issues/11671](https://github.com/adobe/brackets/issues/11671)

I think using [small down triangle](http://stackoverflow.com/questions/2701192/what-characters-can-be-used-for-up-down-triangle-arrow-without-stem-for-displa) '▾' looks better!

```
.CodeMirror-foldgutter-open:after {
  content: "⌵";
  font-size: 1.3em;
  color: #767676;
}
```

to

```
.CodeMirror-foldgutter-open:after {
  content: "▾";
  font-size: 1.3em;
  color: #767676;
}
```

![](http://i.imgur.com/GPvZsCr.jpg)

**Comment by rainje** [comment]
I like my minimal arrow ;)
