### ISSUE TITLE
Undo won't work after save

### ISSUE THREAD

**Issue by brandonellett** [rainje/Monokai-Dark-Soda#7]
After I do a save to an open file I am working on I can't undo anything before the save. I have done some research which mentions that it is an extension issue that is causing the bug/issue. Monokai-Dark-Soda is the only extension that I have running or installed for that matter. 
I guess I should mention that this is for Brackets, but I assume that is a given. 
Any help to fix or point me in the right direction would be great. Thanks.

**Comment by rainje** [comment]
Well I have the issue aswell but it seems to be brackets related. My theme does nothing more than changing css values, there's no js involved or anything that could do this.

https://github.com/adobe/brackets/issues/11826

You can see the bug report is still open and has been for months.
