### ISSUE TITLE
Create Theme

### ISSUE THREAD

**Issue by anandisrocking007** [rainje/Monokai-Dark-Soda#8]
Hello sir i was thinking of creating a new theme for myself but i can not find where can you see all the CSS selectors required for creating the the theme such as .cm-keyword, .cm-qualifier, .cm-builtin or .cm-tag,some themes have more string than even the default brackets theme i cant understand where do you get these.....i know this is the wrong place to write this but i don't know anywhere else to write it..........any help would be appreciated.

**Comment by rainje** [comment]
Hi,

You can get more informations on themes in the codemirror manual : https://codemirror.net/doc/manual.html#styling

Good luck with your theme!

**Comment by anandisrocking007** [comment]
Hello Thank you for the reply i was going through it and i have found few css selector which is unique to your theme can you tell me what it is for 
```
.brackets-git-gutter-added,
.brackets-git-gutter-modified,
.brackets-git-gutter-removed 

```

i believe they are for your bracket git extensions

but i can't under stand what this is for
`.ico-cssColorPreview 
`

Also i am new to PHP i was wondering if you know any good extensions for PHP Hinting ,linting or any other thing.

Last but not the least i love your monokai dark soda theme and have been using for nearly a year  just one small recommendation use a unique color for php .cm-meta selector such as a little orange (#F79900) it helps in telling where the PHP code Start and where it ends faster......Thank you

Also i was wondering if there is a way i can msg you it will just be 1 or 2 problems i might have about this theme.......anyways thankyou again.

**Comment by rainje** [comment]
> .brackets-git-gutter-added,
> .brackets-git-gutter-modified,
> .brackets-git-gutter-removed 

Brackets Git

> .ico-cssColorPreview

Brackets CSs Color Preview

And there's also some var for Match Highlighter. All these extensions are listed on the readme.

I'm not using brackets anymore as it was getting too slow for me. I first switched to Atom then recently to Visual Studio Code so I can't really recommend good extensions for Brackets anymore.

I'll take a look at your suggestion and may push it if it's good.

You can still reach me here if that's theme related ;).
